### ISSUE TITLE
Setting the font size.

### ISSUE THREAD

**Issue by msdian-hub** [johnnywang1994/jsPDF-html2canvas#33]
Hallo. 
I want to set the fixed font size of my html. I am able to get the html in the form of a Grid. But the issue that I am facing is upon download the Grid from the webpage, I am not getting the same size of my grid in pdf. If I zoom out the webpage, then I am getting different size and same as with in Zoom in.

const  downloadTable  = () => {
    var element = document.getElementById('grid');
    html2PDF(element, {
        jsPDF: {unit: 'in', format: 'letter', orientation: 'portrait'},
        image:{ type: 'jpeg', quality: 1 },
        margin: { top: 0, right: 1, bottom: 1, left: 1,},
        html2canvas: {scale: 1 ,useCORS: false,}, 
        output: 'jspdf-generate.pdf', 
        success: function(pdf) {
            pdf.setFontSize(500);    // not working
            pdf.save(this.output);
        } 
    });

}

Is there a way to fixed the size of contents in a page?

**Comment by johnnywang1994** [comment]
hi, thanks for your issue.

Because the plugin will snapshot your html content as image, and auto "resize" the image to fit the PDF layout size, this is the reason why your content can't fix size no matter window zoomed in or not.

I'll add a autoResize option for this as for some use case that needs the content to fix the original size without resizing it.
